"""
This code records audio from the microphone, 
detects the transmitted signal, estimates the channel impulse response (CIR), 
and calculates the distance to a reflector based on the detected peaks in the CIR.
Run sound_generation.py 1st to create training signal, save it as p.npy.

"""
import numpy as np
import sounddevice as sd
from scipy.signal import find_peaks
import matplotlib.pyplot as plt

#Parameters that control the recording and distance estimation

fs = 48000    #must match transmitter phone to convert samples to time
duration = 3.0   #seconds to record (should be long enough to capture echoes)
c = 343.0   #speed of sound (convert time to distance)

#Script loads signal p.npy that was generated by sound_generation.py, normalizes it to ensure it has consistent amplitude.

p = np.load("p.npy")  #reference the training signal for recording and processing
p = p / np.max(np.abs(p))  #normalize


#Record audio for a specified duration

print("Recording...")

rx = sd.rec(int(duration * fs), samplerate=fs, channels=1) #Receive audio from microphone and the echoes will be captured in this recording. 
sd.wait()

rx = rx.flatten()

print("Recording finished")

#Signal alignment using cross-correlation to find where the transmitted signal appears in the recording.

correlation = np.correlate(rx, p, mode='valid')
start_idx = np.argmax(np.abs(correlation)) #Signal first appears at this index in the recording.

print("Signal detected at sample:", start_idx)

#Prevent overflow if the recording is too short.
if start_idx + len(p) > len(rx):
    print("Recording is too short")
    exit()

rx_block = rx[start_idx : start_idx + len(p)] #Extract the segment of the recording that corresponds to the length of the training signal p.

#Channel estimation using FFT to compute the CIR from the transmitted signal and the received block.

X = np.fft.fft(p) #FFT of the transmitted signal (reference signal)
Y = np.fft.fft(rx_block) #FFT of the received block that contains the transmitted signal and its echoes.

epsilon = 1e-6 * np.max(np.abs(X)**2)
H = (np.conj(X) * Y) / (np.abs(X)**2 + epsilon) #Estimate the channel frequency response by dividing the FFT of the received signal by the FFT of the transmitted signal.
h = np.fft.ifft(H) #Compute the channel impulse response (CIR)

mag = np.abs(h) #Magnitude of the CIR, which will be used to detect peaks corresponding to echoes.

#Find the max peaks in CIR  
peaks, _ = find_peaks(mag, distance=20, height=np.max(mag)*0.2)

if len(peaks) < 2:
    print("Need more peaks.")
    exit()

#pick top 2 peaks
top_peaks = peaks[np.argsort(mag[peaks])[-2:]] 
top_peaks = np.sort(top_peaks) #Sort the top peaks to ensure they are in the correct order (1st peak is the direct path, 2nd peak is the echo).

print("Detected peaks at:", top_peaks)

#Ensure the gap between the two peaks is reasnoable.
gap = abs(top_peaks[1] - top_peaks[0]) 
gap = min(gap, len(h) - gap) 

print("Sample gap:", gap)

#Calculate the time delay corresponding to gap
time_delay = gap / fs
extra_path = c * time_delay #Calculate the extra path length corresponding to the time delay.

distance = extra_path / 2

print(f"Extra path length: {extra_path:.4f} m")
print(f"Estimated reflector distance: {distance:.4f} m")

#Plot the CIR and detected peaks for visualization
plt.figure(figsize=(10,4))
plt.plot(mag, label="CIR Magnitude")
plt.plot(top_peaks, mag[top_peaks], 'ro', label="Detected Peaks")
plt.title("Channel Impulse Response (CIR)")
plt.xlabel("Sample Index")
plt.ylabel("Magnitude")
plt.legend()
plt.grid()
plt.show()